export const memoriesLink = 'https://velvety-melba-ecb0f0.netlify.app/'
export const moviesLink = ' https://prismatic-dragon-92727e.netlify.app/'
export const chatLink = 'https://msg-faster.vercel.app/'
export const youtubeLink = 'https://you-tube-clone-three.vercel.app/'
export const googleLink = 'https://google-app-two.vercel.app/'